export enum PermissionId {
  // Ban & unban
  CAN_BAN_AUTHORIZATION = 'CAN_BAN_AUTHORIZATION',
  CAN_UNBAN_AUTHORIZATION = 'CAN_UNBAN_AUTHORIZATION',

  // Role management
  CAN_UPDATE_ROLE = 'CAN_UPDATE_ROLE',
  CAN_DELETE_ROLE = 'CAN_DELETE_ROLE',
  CAN_CREATE_ROLE = 'CAN_CREATE_ROLE',
  CAN_READ_ROLE = 'CAN_READ_ROLE',
}
