// Info: for all token is "secret" used as secret.
export const tokenWithoutExp =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1MTYyMzkwMjJ9.ygbbkdw2ZRJSTyNSL5o8fKNLngAIQTkGsDCM8g6sGrg';
export const expiredToken =
  'eyJhbGciOiJIUzI1NiJ9.eyJpZCI6InRlc3QtaWQiLCJpc1N1cGVyQWRtaW4iOmZhbHNlLCJhcHBzIjpbeyJpc0FkbWluIjpmYWxzZSwiYXBwSWQiOiJjb3JlIiwidGVuYW50SWQiOiIiLCJwZXJtaXNzaW9ucyI6WyJDQU5fVEVTVCJdfSx7ImlzQWRtaW4iOmZhbHNlLCJhcHBJZCI6InRlbmFudCIsInRlbmFudElkIjoib25lIiwicGVybWlzc2lvbnMiOlsiQ0FOX1RFU1QiXX0seyJpc0FkbWluIjpmYWxzZSwiYXBwSWQiOiJ0ZW5hbnQiLCJ0ZW5hbnRJZCI6InR3byIsInBlcm1pc3Npb25zIjpbIkNBTl9URVNUIl19XSwiZXhwIjo5Njc0NjE0NDgsImlhdCI6MTY5MzIxNDI0OH0.FT4Z8JdA4k1kvOS_hHpC9dqSgJ2aIJ-TVTLEQ6xXmUE';
export const validToken =
  'eyJhbGciOiJIUzI1NiJ9.eyJpZCI6InRlc3QtaWQiLCJpc1N1cGVyQWRtaW4iOmZhbHNlLCJhcHBzIjpbeyJpc0FkbWluIjpmYWxzZSwiYXBwSWQiOiJjb3JlIiwidGVuYW50SWQiOiIiLCJwZXJtaXNzaW9ucyI6WyJDQU5fVEVTVCJdfSx7ImlzQWRtaW4iOmZhbHNlLCJhcHBJZCI6InRlbmFudCIsInRlbmFudElkIjoib25lIiwicGVybWlzc2lvbnMiOlsiQ0FOX1RFU1QiXX0seyJpc0FkbWluIjpmYWxzZSwiYXBwSWQiOiJ0ZW5hbnQiLCJ0ZW5hbnRJZCI6InR3byIsInBlcm1pc3Npb25zIjpbIkNBTl9URVNUIl19XSwiZXhwIjozMjUyNDM3MDI0OCwiaWF0IjoxNjkzMjE0MjQ4fQ.b5mY1mhVmMrNX4N_C2cXkQa4fj1sr23oa1iWEhQulho';
export const wrongSecretToken =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1MTYyMzkwMjIsImV4cCI6MzUxNjIzOTAyM30.-1-pNZDfn00yEBFQ0Xn7E54meO5aVTad0j3c8HLlACA';
export const changedToken =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmb28iOiJiYXIiLCJpYXQiOjE1MTYyMzkwMjIsImV4cCI6MzUxNjIzOTAyM30.diRTzgL0xW3dBIC0fqeplrrg9YuvuU9uqq1dvKHCgAs';
