// Info: for all token is "secret" used as secret.
export const tokenWithoutExp =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1MTYyMzkwMjJ9.ygbbkdw2ZRJSTyNSL5o8fKNLngAIQTkGsDCM8g6sGrg';
export const expiredToken =
  'eyJhbGciOiJIUzI1NiJ9.eyJpZCI6InRlc3QtaWQiLCJpc1N1cGVyQWRtaW4iOmZhbHNlLCJwcm92aWRlcnMiOlt7ImlzQWRtaW4iOmZhbHNlLCJwcm92aWRlcklkIjoiY29yZSIsInRlbmFudElkIjoiIiwicGVybWlzc2lvbnMiOlsiQ0FOX1RFU1QiXX0seyJpc0FkbWluIjpmYWxzZSwicHJvdmlkZXJJZCI6InRlbmFudCIsInRlbmFudElkIjoib25lIiwicGVybWlzc2lvbnMiOlsiQ0FOX1RFU1QiXX0seyJpc0FkbWluIjpmYWxzZSwicHJvdmlkZXJJZCI6InRlbmFudCIsInRlbmFudElkIjoidHdvIiwicGVybWlzc2lvbnMiOlsiQ0FOX1RFU1QiXX1dLCJleHAiOjk2NzQ2MTQ0OCwiaWF0IjoxNjkzMjE0MjQ4fQ.oig3OjimBeJ54jYvCvgz40_TSDsFKX9L8r7UDtRuYR0';
export const validToken =
  'eyJhbGciOiJIUzI1NiJ9.eyJpZCI6InRlc3QtaWQiLCJpc1N1cGVyQWRtaW4iOmZhbHNlLCJwcm92aWRlcnMiOlt7ImlzQWRtaW4iOmZhbHNlLCJwcm92aWRlcklkIjoiY29yZSIsInRlbmFudElkIjoiIiwicGVybWlzc2lvbnMiOlsiQ0FOX1RFU1QiXX0seyJpc0FkbWluIjpmYWxzZSwicHJvdmlkZXJJZCI6InRlbmFudCIsInRlbmFudElkIjoib25lIiwicGVybWlzc2lvbnMiOlsiQ0FOX1RFU1QiXX0seyJpc0FkbWluIjpmYWxzZSwicHJvdmlkZXJJZCI6InRlbmFudCIsInRlbmFudElkIjoidHdvIiwicGVybWlzc2lvbnMiOlsiQ0FOX1RFU1QiXX1dLCJleHAiOjMyNTI0MzcwMjQ4LCJpYXQiOjE2OTMyMTQyNDh9.dP25wYfoXMbbmiuVARBsTME9ExN7wIlyckcGF7cJvVA';
export const wrongSecretToken =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1MTYyMzkwMjIsImV4cCI6MzUxNjIzOTAyM30.-1-pNZDfn00yEBFQ0Xn7E54meO5aVTad0j3c8HLlACA';
export const changedToken =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmb28iOiJiYXIiLCJpYXQiOjE1MTYyMzkwMjIsImV4cCI6MzUxNjIzOTAyM30.diRTzgL0xW3dBIC0fqeplrrg9YuvuU9uqq1dvKHCgAs';
